version: '3.8'
services: # apps containers you want to build and run
  pooja_app1: # name of appliction for compose
    image: poojadotnetimg:v1  # image i want to build
    build: .  # path of dockerfile location -- . means current
    container_name: poojac1 # it will create container also
    ports:
    - 1076:80 
  pooja_app2:
    image: poojahttpd:version1
    build:
      context: .
      dockerfile: poojahttpd.dockerfile
    container_name: poojac2
    ports:
    - 1077:80  # you guys can use port between 1024 to 60000
    depends_on:
    - pooja_app1
